global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ea-mt5'
    environment: 'production'

# Alertmanager configuration (opcional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # FastAPI (seu servidor atual)
  - job_name: 'ea-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.15.20:18001']
        labels:
          service: 'fastapi'
          app: 'datacollector'

  # PostgreSQL Exporter (se você instalar)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'postgres'

  # Node Exporter (métricas do sistema Windows)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['windows-exporter:9182']
  #       labels:
  #         service: 'windows'
  #         hostname: 'ea-server'

  # Blackbox Exporter (probe endpoints)
  # - job_name: 'blackbox'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #   static_configs:
  #     - targets:
  #       - http://192.168.15.20:18001/health
  #       - http://192.168.15.20:18001/metrics
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115
