server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # ============================================
  # MT5 Logs
  # ============================================
  - job_name: mt5-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mt5
          app: metatrader5
          __path__: /mt5-logs/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s+(?P<level>\w+)\s+(?P<message>.*)'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006.01.02 15:04:05.000'

  # ============================================
  # EA Logs (Expert Advisor Journal)
  # ============================================
  - job_name: ea-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ea-datacollector
          app: expert-advisor
          __path__: /mt5-logs/**/Experts/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2})\s+(?P<account>\d+)\s+(?P<symbol>\w+)\s+(?P<message>.*)'
      - labels:
          account:
          symbol:
      - timestamp:
          source: timestamp
          format: '2006.01.02 15:04:05'

  # ============================================
  # PowerShell Automation Scripts
  # ============================================
  - job_name: automation-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: automation
          app: powershell
          __path__: /workspace/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            script: script
            message: message
      - labels:
          level:
          script:
      - timestamp:
          source: timestamp
          format: RFC3339

  # ============================================
  # Git Operations
  # ============================================
  - job_name: git-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: git
          app: version-control
          __path__: /workspace/.git/logs/**
    pipeline_stages:
      - regex:
          expression: '^(?P<old_sha>\w+) (?P<new_sha>\w+) (?P<author>.+) <(?P<email>.+)> (?P<timestamp>\d+) (?P<timezone>[+-]\d{4})\t(?P<operation>.+)'
      - labels:
          operation:
          author:
      - timestamp:
          source: timestamp
          format: Unix

  # ============================================
  # Docker Logs (FastAPI container)
  # ============================================
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339

  # ============================================
  # System Logs (Windows Event Logs - se disponível)
  # ============================================
  # - job_name: windows-events
  #   windows_events:
  #     use_incoming_timestamp: true
  #     bookmark_path: "./bookmark.xml"
  #     eventlog_name: "Application"
  #     xpath_query: '*'
  #     labels:
  #       job: windows-events
  #       app: system
  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           source: source
  #           computer: computer
  #           level: level
  #     - labels:
  #         source:
  #         computer:
  #         level:
